### ISSUE TITLE
Database tables defined

### ISSUE THREAD

**Issue by jillianw** [shannonfromomaha/02-29-pair-project#1]
</style>
</head>
<body>

USERS

<table style="width:100%">
  <tr>
    <th>id</th>
    <th>email</th>      
    <th>password</th>
    <th>name</th>
  </tr>
  <tr>
    <td>1</td>
    <td>joe@blah.com</td>       
    <td>catz32!</td>
    <td>Joe Jones</td>
  </tr>
  <tr>
    <td>2</td>
    <td>tom@thing.com</td>      
    <td>banana94</td>
    <td>Tom Thomas</td> 
  </tr>
  <tr>
    <td>3</td>
    <td>sarah@abc.com</td>      
    <td>p0tat0</td>
    <td>Sarah Smith</td>
  </tr>
</table>

</body>
</html>

**Comment by shannonfromomaha** [comment]
Pledge table
user id--user who is pledging money
gift id--gift being contributed to
amount--$$ being pledged
</style>
</head> PLEDGE
<body>

<table style="width:100%">
  <tr>
    <th>id</th>
    <th>user_id</th>        
    <th>gift_id</th>
    <th>amount</th>
  </tr>
  <tr>
    <td>1</td>
    <td>34</td>     
    <td>50</td>
    <td>50.00</td>
  </tr>
  <tr>
    <td>2</td>
    <td>55</td>     
    <td>50</td>
    <td>75.00</td>
  </tr>
  <tr>
    <td>3</td>
    <td>67</td>     
    <td>50</td>
    <td>55.75</td>
  </tr>
</table>

</body>
</html>

**Comment by jillianw** [comment]
**user_id** is the person who decides to start funding a gift for someone
**funded** is a boolean that is FALSE until funding threshold is reached (then TRUE) 

</style>
</head> GIFTS
<body>

<table style="width:100%">
  <tr>
    <th>id</th>
    <th>user_id</th>        
    <th>title</th>
    <th>description</th>
    <th>link</th>
    <th>recipient</th>
    <th>cost</th>
    <th>funded</th>
  </tr>
  <tr>
    <td>1</td>
    <td>522</td>        
    <td>Baby stroller</td>
    <td>Jen is having a baby soon so let's chip in and get her this neat baby mover thing</td>
    <td>www.babiesrus.com/....</td>
    <td>Jen Jones</td>
    <td>$459.99</td>
    <td>FALSE</td>
  </tr>
  <tr>
    <td>2</td>
    <td>3621</td>       
    <td>Six pack and a pound</td>
    <td>Billy is having a super bad week so let's buy him some Taco John's</td>
    <td>www.tacojohns.com/heartburn</td>
    <td>Billy Bradley</td>
    <td>$5.99</td>
    <td>FALSE</td>  
  </tr>
  <tr>
    <td>3</td>
    <td>29</td>     
    <td>Chandelier</td>
    <td>Remember that party that got out of hand and Jane's chandelier that may or may not have been destroyed by us? How about we go ahead and pay to replace it for her.</td>
    <td>www.1stdibs.com/expensive</td>
    <td>Jane Martin</td>
    <td>$2499.00</td>
    <td>FALSE</td>
  </tr>
</table>

</body>
</html>

**Comment by sumeetjain** [comment]
Database looks good.
