### ISSUE TITLE
DuplicateMethodCall(s) in gift.rb model

### ISSUE THREAD

**Issue by jillianw** [shannonfromomaha/02-29-pair-project#44]
- [ ] [35, 35]:DuplicateMethodCall: Gift#set_errors calls self.cost 2 times [https://github.com/troessner/reek/blob/master/docs/Duplicate-Method-Call.md]
- [ ] [32, 32]:DuplicateMethodCall: Gift#set_errors calls self.recipient 2 times [https://github.com/troessner/reek/blob/master/docs/Duplicate-Method-Call.md]
- [ ] [29, 29]:DuplicateMethodCall: Gift#set_errors calls self.title 2 times [https://github.com/troessner/reek/blob/master/docs/Duplicate-Method-Call.md]

**Comment by shannonfromomaha** [comment]
Talked to Alex and decided that in these particular instances, the method needed to be called twice
Example:
`if self.cost == nil || self.cost == 0`
