### ISSUE TITLE
Pledge#self.collect_pledges has approx 7 statements

### ISSUE THREAD

**Issue by jillianw** [shannonfromomaha/02-29-pair-project#52]
- [ ]  [7]:TooManyStatements: Pledge#self.collect_pledges has approx 7 statements [https://github.com/troessner/reek/blob/master/docs/Too-Many-Statements.md]

**Comment by shannonfromomaha** [comment]
weird merge error in 
CONFLICT (content): Merge conflict in coverage/.last_run.json

`{
  "result": {
<<<<<<< HEAD

#     "covered_percent": 34.65

```
"covered_percent": 36.05
```

> > > > > > > master
> > > > > > >   }
> > > > > > > }
> > > > > > > `
