### ISSUE TITLE
PLEDGES

### ISSUE THREAD

**Issue by shannonfromomaha** [shannonfromomaha/02-29-pair-project#6]
**C**
- [x] db schema
- [x] model
- [x] controller
  add controller actions as each new related view/form is created
- [ ] new pledge form (view)
  **R**
- [ ] visible on "view gift" page
- [ ] **U**--VIEW
- [ ] **D**--VIEW

**Comment by sumeetjain** [comment]
Something like "controller" should be broken into pieces–what specifically is involved in that task?

**Comment by jillianw** [comment]
Added: "add controller actions as each new related view/form is created." That's the general process we're going to do.

Does that clarify things enough?

**Comment by shannonfromomaha** [comment]
U and D are actually not useful from a user perspective--we're skipping them for now
