### ISSUE TITLE
pledged_gifts problems with "x"

### ISSUE THREAD

**Issue by jillianw** [shannonfromomaha/02-29-pair-project#61]
- [ ]  [3, 8]:UncommunicativeVariableName: User#pledged_gifts has the variable name 'x' [https://github.com/troessner/reek/blob/master/docs/Uncommunicative-Variable-Name.md]
- [ ]  [4, 8, 9]:FeatureEnvy: User#pledged_gifts refers to x more than self (maybe move it to another class?) [https://github.com/troessner/reek/blob/master/docs/Feature-Envy.md]

**Comment by shannonfromomaha** [comment]
fixed in a different issue
